services:
  sonarqube:
    depends_on:
      db:
        condition: service_healthy
    image: mc1arke/sonarqube-with-community-branch-plugin:${SONARQUBE_VERSION}
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        SONARQUBE_VERSION: ${SONARQUBE_VERSION}
        PLUGIN_VERSION: ${PLUGIN_VERSION}
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
  db:
    image: postgres:16-alpine3.20
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: db
    container_name: postgres
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_conf:
    name: sonarqube_conf
  sonarqube_data:
    name: sonarqube_data
  postgresql:
    name: postgresql
  postgresql_data:
    name: postgresql_data

networks:
  sonarnet:
